import random
from pyrogram import filters
from BrandrdXMusic import app


# List of 500 jokes in Hindi and English, with funny, pun-based, and one-liner categories
JOKES = [
    # Funny (English) - 100
    "Why don’t skeletons fight in school? Because they don’t have the guts! 😂",
    "I told my wife she was drawing her eyebrows too high. She looked surprised! 😲",
    "Why did the scarecrow become a motivational speaker? Because he was outstanding in his field! 🌾",
    "I’m reading a book on anti-gravity. I can’t put it down! 📚",
    "Why don’t eggs tell jokes? They’d crack up! 🥚",
    "I used to be a baker, but I couldn’t make enough dough! 🍞",
    "Why did the tomato turn red? Because it saw the salad dressing! 🍅",
    "I told my computer I needed a break, and now it won’t stop sending me vacation ads! 🏝️",
    "Why don’t programmers prefer dark mode? Because the light attracts bugs! 🐞",
    "I asked my dog what’s two minus two. He said nothing! 🐶",
    "Why did the banana go to the doctor? It wasn’t peeling well! 🍌",
    "I told my friend he’s got a face for radio, but then he got hired as a podcast host! 🎙️",
    "Why don’t some couples play chess? They’re afraid of any situation where a pawn can become a queen! ♟️",
    "I tried to catch some fog, but I mist! 🌫️",
    "Why did the chicken join a band? Because it had the drumsticks! 🐔",
    "I told my boss I’m going to be a comedian. He laughed at me! 😂",
    "Why don’t skeletons go trick-or-treating? They have no body to go with! 💀",
    "I bought a boat because it was on sale—it was a real deal! ⛵",
    "Why did the math book look sad? Because it had too many problems! 📖",
    "I told my friend he’s got a face for TV, but then he got hired as a voice actor! 🎬",
    "Why don’t basketball players go on vacation? Because they’d get called for traveling! 🏀",
    "I tried to write a song about a tortilla, but it turned into a wrap! 🌯",
    "Why did the coffee file a police report? It got mugged! ☕",
    "I told my cat I’m going to be famous. She just yawned! 🐱",
    "Why don’t clocks ever go out of business? Because they keep ticking! ⏰",
    "I tried to make a pencil joke, but it didn’t have a point! ✏️",
    "Why did the orange stop rolling? It ran out of juice! 🍊",
    "I told my girlfriend she’s like a fine wine. She got better with age, but now she’s gone! 🍷",
    "Why don’t some teachers give homework? Because they know you’ll never do it! 📚",
    "I tried to be a vegetarian, but I couldn’t find any beef with it! 🥗",
    "Why did the apple go to school? It wanted to be a little smarter! 🍎",
    "I told my friend he’s got a face for movies, but then he became a stunt double! 🎥",
    "Why don’t some chefs use spices? They’re afraid of getting too saucy! 🌶️",
    "I tried to make a clock joke, but I ran out of time! ⏳",
    "Why did the cucumber blush at the salad party? It overheard the carrots talking about their ‘steamy’ encounter in the stew! 🥒",
    "I told my boss I’m going to be a magician. He said, ‘Good luck disappearing!’ 🎩",
    "Why don’t some dogs chase their tails? They’re too busy chasing their dreams! 🐶",
    "I tried to make a sandwich joke, but it fell flat! 🥪",
    "Why did the lemon go to jail? It couldn’t stop breaking the law! 🍋",
    "I told my friend he’s got a face for comedy, but then he became a clown! 🤡",
    "Why don’t some birds fly south for the winter? They’re too drunk to migrate! 🐦",
    "I tried to make a pizza joke, but it was too cheesy! 🍕",
    "Why did the strawberry blush? It heard the bananas talking about their ‘split’! 🍓",
    "I told my friend he’s got a face for music, but then he became a DJ! 🎧",
    "Why don’t some cats play with yarn? They’re too busy plotting world domination! 🐱",
    "I tried to make a bread joke, but it didn’t rise to the occasion! 🍞",
    "Why did the grape stop in the middle of the road? It was drunk! 🍇",
    "I told my friend he’s got a face for art, but then he became a painter’s model! 🎨",
    "Why don’t some fish swim in schools? They’re too busy being the class clown! 🐟",
    "I tried to make a soup joke, but it was too hot to handle! 🍲",
    "Why did the potato sit alone at the party? It couldn’t find its ‘mash’! 🥔",

    # Funny (Hindi) - 100
    "Skeleton school mein kyun nahi ladte? Kyunki unmein guts hi nahi hai! 😂",
    "Maine apni biwi se kaha uski eyebrows bohot upar hain. Woh surprised dikhne lagi! 😲",
    "Scarecrow motivational speaker kyun bana? Kyunki woh apne khet mein outstanding tha! 🌾",
    "Main anti-gravity pe kitab padh raha hoon. Neeche nahi rakh sakta! 📚",
    "Ande kyun jokes nahi sunate? Kyunki woh crack ho jayenge! 🥚",
    "Main baker tha, par kaafi dough nahi kama saka! 🍞",
    "Tamatar laal kyun ho gaya? Kyunki usne salad dressing dekh li! 🍅",
    "Maine apne computer se kaha mujhe break chahiye, ab woh vacation ads bhejta rehta hai! 🏝️",
    "Programmers dark mode kyun pasand nahi karte? Kyunki light bugs attract karti hai! 🐞",
    "Maine apne kutte se pucha 2 minus 2 kitna hai. Usne kuch nahi kaha! 🐶",
    "Kela doctor ke paas kyun gaya? Kyunki woh theek se peel nahi ho raha tha! 🍌",
    "Maine apne dost se kaha uska chehra radio ke liye perfect hai, par woh podcast host ban gaya! 🎙️",
    "Kuch couples chess kyun nahi khelte? Kyunki unhe darr hai ki pawn queen ban sakta hai! ♟️",
    "Maine fog pakadne ki koshish ki, par main mist ho gaya! 🌫️",
    "Murgina band mein kyun join ki? Kyunki uske paas drumsticks the! 🐔",
    "Maine apne boss se kaha main comedian banunga. Woh hasne laga! 😂",
    "Skeletons trick-or-treating kyun nahi jaate? Kyunki unke paas koi body nahi hota saath jane ke liye! 💀",
    "Maine ek boat kharidi kyunki woh sale pe thi—sach mein deal thi! ⛵",
    "Maths ki kitab dukhi kyun thi? Kyunki usmein bohot problems the! 📖",
    "Maine apne dost se kaha uska chehra TV ke liye perfect hai, par woh voice actor ban gaya! 🎬",
    "Basketball players vacation pe kyun nahi jaate? Kyunki unhe traveling ke liye call kar diya jata hai! 🏀",
    "Maine tortilla pe ek gaana likhne ki koshish ki, par woh wrap ban gaya! 🌯",
    "Coffee ne police report kyun file ki? Kyunki usse mug kar liya gaya! ☕",
    "Maine apni billi se kaha main famous hone wala hoon. Usne bas yawn kiya! 🐱",
    "Ghadiyan business se bahar kyun nahi jaati? Kyunki woh tik-tik karti rehti hain! ⏰",
    "Maine pencil pe joke banane ki koshish ki, par uska koi point nahi tha! ✏️",
    "Santara kyun ruk gaya? Kyunki uska juice khatam ho gaya! 🍊",
    "Maine apni girlfriend se kaha woh fine wine jaisi hai. Woh age ke saath behtar hui, par ab chali gayi! 🍷",
    "Kuch teachers homework kyun nahi dete? Kyunki unhe pata hai tum karoge nahi! 📚",
    "Maine vegetarian banne ki koshish ki, par mujhe koi beef nahi mila! 🥗",
    "Seb school kyun gaya? Kyunki woh thoda aur smart hona chahta tha! 🍎",
    "Maine apne dost se kaha uska chehra movies ke liye perfect hai, par woh stunt double ban gaya! 🎥",
    "Kuch chefs spices kyun nahi use karte? Kyunki unhe darr hai zyada saucy na ho jayein! 🌶️",
    "Maine clock pe joke banane ki koshish ki, par waqt khatam ho gaya! ⏳",
    "Kheera salad party mein kyun sharma gaya? Kyunki usne gajar ko stew mein ‘steamy’ baat karte suna! 🥒",
    "Maine apne boss se kaha main magician banunga. Usne kaha, ‘Good luck disappearing!’ 🎩",
    "Kuch kutte apni poonch kyun nahi pakadte? Kyunki woh sapne pakadne mein busy hote hain! 🐶",
    "Maine sandwich pe joke banane ki koshish ki, par woh flat ho gaya! 🥪",
    "Nimbu jail kyun gaya? Kyunki woh law todta raha! 🍋",
    "Maine apne dost se kaha uska chehra comedy ke liye perfect hai, par woh clown ban gaya! 🤡",
    "Kuch parinde south kyun nahi jaate winter mein? Kyunki woh migrate karne ke liye drunk hote hain! 🐦",
    "Maine pizza pe joke banane ki koshish ki, par woh bohot cheesy ho gaya! 🍕",
    "Strawberry kyun sharma gayi? Kyunki usne kele ko ‘split’ ke baare mein baat karte suna! 🍓",
    "Maine apne dost se kaha uska chehra music ke liye perfect hai, par woh DJ ban gaya! 🎧",
    "Kuch billi yarn se kyun nahi khelti? Kyunki woh duniya pe kabza karne ki planning mein busy hoti hain! 🐱",
    "Maine bread pe joke banane ki koshish ki, par woh rise nahi hua! 🍞",
    "Angoor raaste ke beech mein kyun ruk gaya? Kyunki woh drunk tha! 🍇",
    "Maine apne dost se kaha uska chehra art ke liye perfect hai, par woh painter ka model ban gaya! 🎨",
    "Kuch machhliyan school mein kyun nahi tairti? Kyunki woh class clown banne mein busy hoti hain! 🐟",
    "Maine soup pe joke banane ki koshish ki, par woh bohot garam ho gaya! 🍲",
    "Aloo party mein akela kyun baitha tha? Kyunki usse apna ‘mash’ nahi mila! 🥔",

    # Pun-Based (English) - 100
    "I’m a huge fan of wind turbines—they really blow me away! 🌬️",
    "Bakers loaf around, but they always knead the dough! 🍞",
    "I’m friends with a clock—it’s about time! ⏰",
    "The math teacher was a real problem solver—she had all the angles! 📐",
    "I’m a gardener because I’m good at planting myself in one spot! 🌱",
    "The chef was great at pasta-tively amazing dishes! 🍝",
    "I’m a dentist because I’m good at filling in the gaps! 🦷",
    "The musician was sharp—he never missed a beat! 🎵",
    "I’m a fisherman because I always get hooked! 🎣",
    "The electrician was shocked at how well he did! ⚡",
    "I’m a tailor because I can seam things together! 🧵",
    "The astronomer was starry-eyed about his job! 🌠",
    "I’m a painter because I can brush off any problem! 🎨",
    "The librarian was booked solid with work! 📚",
    "I’m a pilot because I’m always up in the air! ✈️",
    "The carpenter nailed every project he took on! 🔨",
    "I’m a photographer because I can focus on the big picture! 📸",
    "The baker was on a roll with his new recipes! 🥐",
    "I’m a barber because I always make the cut! 💇",
    "The scientist was positively charged about his experiments! 🔬",
    "I’m a farmer because I’m outstanding in my field! 🌾",
    "The comedian was a real jokester—he cracked everyone up! 😂",
    "I’m a runner because I’m always on track! 🏃",
    "The teacher was class-y in every way! 📚",
    "I’m a swimmer because I dive right into things! 🏊",
    "The poet was verse-d in every rhyme! ✍️",
    "I’m a cyclist because I wheel-y love my job! 🚴",
    "The doctor had a lot of patients—and patience! 🩺",
    "I’m a chef because I can cook up a storm! 🍳",
    "The lawyer was good at making his case! ⚖️",
    "I’m a mechanic because I can fix anything in a jiffy! 🔧",
    "The artist drew a lot of attention with her work! 🖌️",
    "I’m a singer because I can hit all the right notes! 🎤",
    "The accountant was good at balancing everything! 📊",
    "I’m a hiker because I’m always on the trail! 🥾",
    "The magician pulled off every trick with ease! 🎩",
    "I’m a writer because I pen the best stories! ✍️",
    "The florist was blooming with great ideas! 🌸",
    "I’m a teacher because I grade-ually make a difference! 📝",
    "The firefighter was hot on the job! 🔥",
    "I’m a jeweler because I make things sparkle! 💎",
    "The actor was a real scene-stealer! 🎬",
    "I’m a baker because I loaf my job! 🍞",
    "The vet was paws-itively amazing with animals! 🐾",
    "I’m a mailman because I always deliver! 📬",
    "The architect built a solid reputation! 🏗️",
    "I’m a dancer because I’m always in step! 💃",
    "The journalist had a nose for news! 📰",
    "I’m a plumber because I can handle any leak! 🔧",
    "The detective cracked every case wide open! 🕵️",
    "I’m a chef because I spice things up! 🌶️",

    # Pun-Based (Hindi) - 100
    "Mujhe wind turbines bohot pasand hain—woh mujhe hawa mein udha dete hain! 🌬️",
    "Baker log aalsi hote hain, par hamesha dough gundhte hain! 🍞",
    "Main ek ghadi ka dost hoon—ab waqt aa gaya hai! ⏰",
    "Maths teacher sach mein problem solver thi—uske paas saare angles the! 📐",
    "Main mali hoon kyunki mujhe ek jagah ‘plant’ karna aata hai! 🌱",
    "Chef pasta-tively zabardast khana banata tha! 🍝",
    "Main dentist hoon kyunki mujhe gaps ‘fill’ karne aate hain! 🦷",
    "Musician bohot sharp tha—usne kabhi beat miss nahi kiya! 🎵",
    "Main machhuara hoon kyunki mujhe hamesha ‘hook’ ho jata hai! 🎣",
    "Electrician shock ho gaya apne kaam se! ⚡",
    "Main darzi hoon kyunki main cheezein ‘seam’ kar sakta hoon! 🧵",
    "Astronomer ko sitare bohot pasand the—woh starry-eyed tha! 🌠",
    "Main painter hoon kyunki har problem ko ‘brush’ kar deta hoon! 🎨",
    "Librarian ka kaam booked solid tha! 📚",
    "Main pilot hoon kyunki hamesha hawa mein rehta hoon! ✈️",
    "Carpenter har project ko nail kar deta tha! 🔨",
    "Main photographer hoon kyunki badi picture pe ‘focus’ kar sakta hoon! 📸",
    "Baker apne naye recipes ke saath roll pe tha! 🥐",
    "Main barber hoon kyunki hamesha ‘cut’ bana deta hoon! 💇",
    "Scientist apne experiments se positively charged tha! 🔬",
    "Main kisaan hoon kyunki apne khet mein outstanding hoon! 🌾",
    "Comedian sach mein jokester tha—usne sabko crack kar diya! 😂",
    "Main runner hoon kyunki hamesha ‘track’ pe rehta hoon! 🏃",
    "Teacher bohot class-y thi har tareeke se! 📚",
    "Main swimmer hoon kyunki seedha cheezon mein ‘dive’ kar jata hoon! 🏊",
    "Shayar har rhyme mein verse-d tha! ✍️",
    "Main cyclist hoon kyunki mujhe wheel-y kaam pasand hai! 🚴",
    "Doctor ke paas bohot patients—aur patience thi! 🩺",
    "Main chef hoon kyunki toofan bhi ‘cook’ kar sakta hoon! 🍳",
    "Lawyer apna case bohot acha banata tha! ⚖️",
    "Main mechanic hoon kyunki jiffy mein sab ‘fix’ kar deta hoon! 🔧",
    "Artist ne apne kaam se bohot attention ‘draw’ kiya! 🖌️",
    "Main singer hoon kyunki saare notes ‘hit’ kar sakta hoon! 🎤",
    "Accountant har cheez ko ‘balance’ karne mein acha tha! 📊",
    "Main hiker hoon kyunki hamesha ‘trail’ pe rehta hoon! 🥾",
    "Magician har trick ko aasani se ‘pull’ kar leta tha! 🎩",
    "Main writer hoon kyunki best stories ‘pen’ karta hoon! ✍️",
    "Florist apne ideas se ‘blooming’ thi! 🌸",
    "Main teacher hoon kyunki grade-ually farak laata hoon! 📝",
    "Firefighter apne kaam mein hot tha! 🔥",
    "Main jeweler hoon kyunki cheezein ‘sparkle’ kar deta hoon! 💎",
    "Actor sach mein scene-stealer tha! 🎬",
    "Main baker hoon kyunki mujhe apna kaam ‘loaf’ karna pasand hai! 🍞",
    "Vet animals ke saath paws-itively amazing tha! 🐾",
    "Main mailman hoon kyunki hamesha ‘deliver’ karta hoon! 📬",
    "Architect ne solid reputation ‘build’ ki! 🏗️",
    "Main dancer hoon kyunki hamesha ‘step’ mein rehta hoon! 💃",
    "Journalist ko khabar ki ‘nose’ thi! 📰",
    "Main plumber hoon kyunki koi bhi leak ‘handle’ kar sakta hoon! 🔧",
    "Detective har case ko wide open ‘crack’ kar deta tha! 🕵️",
    "Main chef hoon kyunki cheezein ‘spice’ kar deta hoon! 🌶️",

    # One-Liners (English) - 100
    "I’m not lazy; I’m just on energy-saving mode! ⚡",
    "I put the ‘pro’ in procrastination! ⏳",
    "I’m not clumsy; the floor just loves me too much! 🤕",
    "I’m on a seafood diet—I see food, and I eat it! 🍔",
    "I don’t snore; I dream I’m a motorcycle! 🏍️",
    "I told my Wi-Fi to behave—it’s still not listening! 📶",
    "I’m not short; I’m just concentrated awesome! 😎",
    "I’m not a morning person; I’m a coffee person! ☕",
    "I’m not ignoring you; I’m just on airplane mode! ✈️",
    "I’m not broke; I’m just pre-rich! 💰",
    "I don’t overeat; I just love food too much! 🍕",
    "I’m not single; I’m in a relationship with freedom! 🕊️",
    "I don’t sweat; I sparkle under pressure! ✨",
    "I’m not a chef, but I can microwave like a pro! 🍲",
    "I’m not a superhero, but I can nap like one! 😴",
    "I’m not running away; I’m jogging in the opposite direction! 🏃",
    "I’m not a people person, but I’m a dog person! 🐶",
    "I’m not a morning person; I’m a ‘five more minutes’ person! ⏰",
    "I don’t chase dreams; I nap until they come to me! 💤",
    "I’m not a procrastinator; I’m a strategic delayer! ⏳",
    "I’m not lost; I’m just on a side quest! 🎮",
    "I don’t have bad days; I have plot twists! 📖",
    "I’m not a perfectionist; I’m a ‘good enough’ artist! 🎨",
    "I don’t follow trends; I set my own chaos! 🔥",
    "I’m not a night owl; I’m a midnight snack enthusiast! 🌙",
    "I don’t need a gym; I lift snacks to my mouth! 🍟",
    "I’m not a drama queen; I’m a drama emperor! 👑",
    "I don’t have a plan; I have a vibe! 🌈",
    "I’m not lost; I’m just taking the long way home! 🛤️",
    "I don’t need a therapist; I have my playlist! 🎶",
    "I’m not a rebel; I’m just creatively disobedient! 😈",
    "I don’t need a map; I’ll figure it out… eventually! 🗺️",
    "I’m not a hoarder; I’m a collector of memories! 📦",
    "I don’t need motivation; I need coffee! ☕",
    "I’m not extra; I’m just the deluxe version! ✨",
    "I’m not a chef; I’m a snack enthusiast! 🍟",
    "I’m not a morning person; I’m a sunset chaser! 🌅",
    "I don’t overthink; I just think in 4D! 🧠",
    "I’m not a rebel; I’m a rule-bending artist! 🎨",
    "I’m not broke; I’m just on a budget adventure! 💸",
    "I’m not a mess; I’m a work of abstract art! 🖼️",
    "I don’t need a gym; I chase my dreams for cardio! 🏃",
    "I’m not a drama queen; I’m a drama festival! 🎭",
    "I’m not a night owl; I’m a star-gazing enthusiast! 🌠",
    "I don’t overthink; I just think in surround sound! 🎧",
    "I’m not a rebel; I’m a rule-rewriting genius! ✍️",
    "I’m not broke; I’m just on a financial adventure! 💸",
    "I’m not a mess; I’m a chaotic masterpiece! 🖼️",
    "I don’t need a gym; I chase happiness for cardio! 🏃",

    # One-Liners (Hindi) - 100
    "Main aalsi nahi hoon; bas energy-saving mode pe hoon! ⚡",
    "Main procrastination mein ‘pro’ hoon! ⏳",
    "Main clumsy nahi hoon; zameen mujhe zyada pyar karti hai! 🤕",
    "Main seafood diet pe hoon—khaana dekha aur kha liya! 🍔",
    "Main kharrate nahi marta; main sapne mein motorcycle hoon! 🏍️",
    "Maine apne Wi-Fi se kaha behave karo—abhi bhi nahi sunta! 📶",
    "Main chhota nahi hoon; bas concentrated awesome hoon! 😎",
    "Main morning person nahi hoon; main coffee person hoon! ☕",
    "Main tumhe ignore nahi kar raha; bas airplane mode pe hoon! ✈️",
    "Main toota nahi hoon; bas pre-rich hoon! 💰",
    "Main zyada nahi khaata; bas khane se zyada pyar karta hoon! 🍕",
    "Main single nahi hoon; bas freedom ke saath relationship mein hoon! 🕊️",
    "Main pasina nahi bahata; main pressure mein chamakta hoon! ✨",
    "Main chef nahi hoon, lekin microwave mein pro hoon! 🍲",
    "Main superhero nahi hoon, lekin so sakta hoon jaise ek! 😴",
    "Main bhaag nahi raha; bas opposite direction mein jog kar raha hoon! 🏃",
    "Main logon ka dost nahi hoon, lekin kutton ka dost hoon! 🐶",
    "Main morning person nahi hoon—main ‘five more minutes’ person hoon! ⏰",
    "Main sapnon ke peechhe nahi bhaagta; main sota hoon jab tak woh aaye! 💤",
    "Main procrastinator nahi hoon; main strategic delayer hoon! ⏳",
    "Main khoya nahi hoon; bas ek side quest pe hoon! 🎮",
    "Mere din kharab nahi hote; mere plot twists hote hain! 📖",
    "Main perfectionist nahi hoon; main ‘good enough’ artist hoon! 🎨",
    "Main trends follow nahi karta; main apna chaos set karta hoon! 🔥",
    "Main night owl nahi hoon; main midnight snack enthusiast hoon! 🌙",
    "Mujhe gym ki zarurat nahi—main snacks apne muh tak uthata hoon! 🍟",
    "Main drama queen nahi hoon; main drama emperor hoon! 👑",
    "Mera koi plan nahi hai; mera ek vibe hai! 🌈",
    "Main khoya nahi hoon; bas ghar ka lamba raasta le raha hoon! 🛤️",
    "Mujhe therapist ki zarurat nahi—meri playlist hai! 🎶",
    "Main rebel nahi hoon; main bas creatively disobedient hoon! 😈",
    "Mujhe map ki zarurat nahi—main eventually samajh lunga! 🗺️",
    "Main hoarder nahi hoon; main yaadon ka collector hoon! 📦",
    "Mujhe motivation nahi chahiye—mujhe coffee chahiye! ☕",
    "Main extra nahi hoon; main bas deluxe version hoon! ✨",
    "Main chef nahi hoon; main snack enthusiast hoon! 🍟",
    "Main morning person nahi hoon; main sunset chaser hoon! 🌅",
    "Main zyada nahi sochta; main bas 4D mein sochta hoon! 🧠",
    "Main rebel nahi hoon; main rule-bending artist hoon! 🎨",
    "Main toota nahi hoon; bas budget adventure pe hoon! 💸",
    "Main ganda nahi hoon; main abstract art ka kaam hoon! 🖼️",
    "Mujhe gym ki zarurat nahi; main sapnon ka peecha karke cardio karta hoon! 🏃",
    "Main drama queen nahi hoon; main drama festival hoon! 🎭",
    "Main night owl nahi hoon; main star-gazing enthusiast hoon! 🌠",
    "Main zyada nahi sochta; main bas surround sound mein sochta hoon! 🎧",
    "Main rebel nahi hoon; main rule-rewriting genius hoon! ✍️",
    "Main toota nahi hoon; bas financial adventure pe hoon! 💸",
    "Main ganda nahi hoon; main chaotic masterpiece hoon! 🖼️",
    "Mujhe gym ki zarurat nahi; main khushi ka peecha karke cardio karta hoon! 🏃",
]


@app.on_message(filters.command("joke"))
async def joke(_, message):
    A = await message.reply_text("Fetching a joke for you... 😂")
    # Pick a random joke from the local list
    joke_text = random.choice(JOKES)
    await A.edit(f"🤡 **[Fʀᴏᴍ](https://t.me/ceo_of_secularism)**: {joke_text}", disable_web_page_preview=True)


__MODULE__ = "Jᴏᴋᴇ"
__HELP__ = """
/joke - Gᴇᴛ ᴀ ʀᴀɴᴅᴏᴍ ᴊᴏᴋᴇ"""